### ISSUE TITLE
Bot will not connect

### ISSUE THREAD

**Issue by pwlgrzs** [cjavad/lgsm-discord#11]
Hi, I am trying to set up the bot on my server, but it is not connecting to Discord regardless of correct bot token used.

**Comment by cjavad** [comment]
Hi @pwlgrzs , i suppose the output you were expecting ei. `lgsm-discord: connected` did not appear in the console when running `node bot.js`.

Full disclosure: I am not actively maintaining this project, but if there is a bug i would not be against patching it.

**Comment by pwlgrzs** [comment]
Hi @cjavad, my JS skills are not that good, but when I was looking at this in the morning part of yourcode suggested I'd see that in the console. Bot also does not appear to be logged in, I am sure token is right, I also tried to enclose it in "" but that didn't help much.

**Comment by cjavad** [comment]
Closed -issue cannot be duplicated.
