### ISSUE TITLE
Still compatible? Help message not working.

### ISSUE THREAD

**Issue by mrc4tt** [cjavad/lgsm-discord#3]
Hello,

Does this work still?

Does it support multiple game servers?
Example:
/home/user/servers/srv1/srv1 commandhere
/home/user/servers/srv2/srv2 commandhere

BOT on Discord:
!srv1 start
!srv2 start

**Comment by cjavad** [comment]
Yes servers are filtered by the name in the configuration file. But the bot needs to be hosted on each server but using the same bot token it appears as one bot.

**Comment by mrc4tt** [comment]
Hmm, I see.

Seems BOT don't answer me, I'm pretty sure I did setup "anything" correctly.

```
user: (shell user I think?)
access (Client's ID on discord?)
    servers: [{
            path: '/home/fsh/servers/gold1/gold1',
            pubIp: '95.156.228.10:27015',
            name: 'gold1'
        },
```
So, it should work, if I typo: $gold1 status (Since the prefix is $).

**Updated....12:58**
Seems I got it working, after typo: $gold1 status

Could be nice, if we can make, so $help command will work =) so it will display which commands are possible (As an example!)

```
        var helpMessage = `Usage: ${config.prefix}[server] [command]?\n**Valid Commands:**\n\`\`\``;
        commands.forEach(cmd => {
            helpMessage += `${cmd.short.length <= 1 ? pad('  ', cmd.short, false) : cmd.short} ${cmd.command} \n`;
        });
        helpMessage += "```"
        message.channel.send(helpMessage);
```
How will this work? - I don't get any output if I using help or commands.

**Comment by cjavad** [comment]
I'll be updating documentation soon, I'll let you know here.

**Comment by mrc4tt** [comment]
@cjavad Let me know! =)

It should be possible to get "output" about "Valid Commands" via $help (as an example), but nothing happens.

**Comment by cjavad** [comment]
@MikkelDK should be fixed now, did some light testing, $h and $help should now invoke the help message. Closing to address this change.
