### ISSUE TITLE
[Idea/Suggestion] $servers

### ISSUE THREAD

**Issue by mrc4tt** [cjavad/lgsm-discord#4]
This is just an idea/suggestion.

Adding $servers as a command.
So it could list up: "Which servers" is added via config.ini and checking about "server" is online or offline! =)

Mikkel: $servers
BOT: (embeds mode):
Server List:
```
==========
Mikkel: ✔Online.
Test: ❌Offline.
==========
```
Example:
![example](https://i.imgur.com/qsdUDbW.png)

**Just an eg what it could be!**

**Comment by cjavad** [comment]
@MikkelDK pinging each server could prove to be a performance issue if you have 4+ servers setup, and since configs are stored across multiple servers, making a simple embed would be quite the challenge. 

Will attempt to list both status and server name.

**Comment by cjavad** [comment]
@MikkelDK feel free to format the final result as much as you want and submit a PR.
