### ISSUE TITLE
[Suggestion] A few idea.

### ISSUE THREAD

**Issue by mrc4tt** [cjavad/lgsm-discord#5]
I did made, so only "_h / help_" as the command will be deleted, after typo: ``$h OR $help``

Could be nice, if I type "command" will be removed instantly If we say:
$serveralias status ``//That will be removed and BOT will reply still``

Make it possible "editable" via config.ini, so we can choose: 
``$srv1 command`` OR ``$command srv1``
``$srv1 start`` OR ``$start srv1``

Remove "output" from these commands: ``Start, Stop and Restart``
Make custom BOT-Message after using ``Start, Stop and Restart``

**Example of how it will look:**

> USER: $srv1 start
> BOT: Starting srv1......... 
> BOT (deleting message: Starting srv1.....)
> BOT: The server should be online.
> 
> USER: $srv1 restart
> BOT: Restarting srv1......
> BOT (deleting message: Restarting srv1.....)
> BOT: The server should be online, after restarting!
> 
> USER: $srv1 stop
> BOT: Stopping srv1......
> BOT (deleting message: Stopping srv1.....)
> BOT: The server should be offline.

**Comment by mrc4tt** [comment]
@cjavad do you think this is possible? - I'm willing to offer some cash. =D

**Comment by cjavad** [comment]
@MikkelDK it's doable that's for sure I have been short of time recently but I'll give it a go now.

As for money feel free to donate money via Patreon or PayPal. You can also DM me on twitter/discord if you wanna discuss this project in details at \@javadshafique and apple#0018

**Comment by cjavad** [comment]
Implemented as of 236a1c5
